"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Check } from "lucide-react";
import { useCloudLab } from "@/components/provider";
import { statusOf } from "@/lib/status";

export default function Manage() {
  const { store, user, ready, update } = useCloudLab();
  const router = useRouter();
  const allowed = user?.role === "employee" || user?.role === "administrator";
  const [tab, setTab] = useState<"services"|"equipment"|"requests"|"users">("services");
  useEffect(() => { if (ready && !allowed) router.push("/login"); }, [ready, allowed, router]);
  if (!ready || !allowed) return <div className="page container">Checking access…</div>;
  const updateService = (id:string, key:string, value:string|number|boolean) => update(s => ({...s, services:s.services.map(x=>x.id===id?{...x,[key]:value}:x)}));
  return <main className="page"><div className="container"><span className="eyebrow">Data management</span><h1 className="section-title mt-3">Prototype operations.</h1><p className="muted mt-3">Edit browser-local data. Changes synchronize to other open tabs.</p><div className="mt-7 flex flex-wrap gap-2">{(["services","equipment","requests",...(user.role==="administrator"?["users"]:[])] as typeof tab[]).map(t=><button className={`btn capitalize ${tab===t?"btn-dark":""}`} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {tab==="services"&&<section className="card table-wrap mt-5 p-5"><table><thead><tr><th>Service</th><th>Description</th><th>Price</th><th>Days</th><th>Published</th></tr></thead><tbody>{store.services.map(s=><tr key={s.id}><td><input aria-label="Service title" className="input min-w-56" value={s.title} onChange={e=>updateService(s.id,"title",e.target.value)}/></td><td><input aria-label="Service description" className="input min-w-72" value={s.description} onChange={e=>updateService(s.id,"description",e.target.value)}/></td><td><input aria-label="Price" className="input w-28" type="number" value={s.price} onChange={e=>updateService(s.id,"price",Number(e.target.value))}/></td><td><input aria-label="Turnaround" className="input w-20" type="number" value={s.turnaround} onChange={e=>updateService(s.id,"turnaround",Number(e.target.value))}/></td><td><input type="checkbox" checked={s.published} onChange={e=>updateService(s.id,"published",e.target.checked)}/></td></tr>)}</tbody></table></section>}
  {tab==="equipment"&&<section className="card mt-5 grid gap-4 p-5 md:grid-cols-2">{store.equipment.map(e=><div className="rounded-2xl border p-4" key={e.id}><b>{e.short} · {e.name}</b><label className="label mt-4">Operating state</label><select className="input" value={e.state} onChange={ev=>update(s=>({...s,equipment:s.equipment.map(x=>x.id===e.id?{...x,state:ev.target.value as typeof e.state}:x)}))}><option>Online</option><option>Maintenance</option><option>Offline</option></select><label className="label mt-4">Monetizable capacity: {e.capacity}%</label><input className="w-full accent-red-600" type="range" min="0" max="100" value={e.capacity} onChange={ev=>update(s=>({...s,equipment:s.equipment.map(x=>x.id===e.id?{...x,capacity:Number(ev.target.value),utilization:100-Number(ev.target.value)}:x)}))}/></div>)}</section>}
  {tab==="requests"&&<section className="card table-wrap mt-5 p-5"><table><thead><tr><th>Request</th><th>Status</th><th>Claimed by</th><th>Customer note</th><th></th></tr></thead><tbody>{store.requests.map(r=><tr key={r.id}><td><b>{r.number}</b></td><td>{statusOf(r).name}</td><td><select className="input min-w-40" value={r.claimedBy||""} onChange={e=>update(s=>({...s,requests:s.requests.map(x=>x.id===r.id?{...x,claimedBy:e.target.value||undefined}:x)}))}><option value="">Unclaimed</option>{store.users.filter(u=>u.role!=="customer").map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></td><td><input className="input min-w-64" value={r.note||""} onChange={e=>update(s=>({...s,requests:s.requests.map(x=>x.id===r.id?{...x,note:e.target.value}:x)}))}/></td><td><button disabled={statusOf(r).name==="Completed"} className="btn btn-primary !px-3" onClick={()=>update(s=>({...s,requests:s.requests.map(x=>x.id===r.id?{...x,forcedComplete:true,resultReadyAt:Date.now()}:x)}))}><Check size={15}/>Complete</button></td></tr>)}</tbody></table>{!store.requests.length&&<p className="muted py-10 text-center">No requests to manage.</p>}</section>}
  {tab==="users"&&<section className="card table-wrap mt-5 p-5"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Company</th></tr></thead><tbody>{store.users.map(u=><tr key={u.id}><td><input className="input" value={u.name} onChange={e=>update(s=>({...s,users:s.users.map(x=>x.id===u.id?{...x,name:e.target.value}:x)}))}/></td><td>{u.email}</td><td><select className="input" value={u.role} onChange={e=>update(s=>({...s,users:s.users.map(x=>x.id===u.id?{...x,role:e.target.value as typeof u.role}:x)}))}><option>customer</option><option>employee</option><option>administrator</option></select></td><td><input className="input" value={u.company||""} onChange={e=>update(s=>({...s,users:s.users.map(x=>x.id===u.id?{...x,company:e.target.value}:x)}))}/></td></tr>)}</tbody></table></section>}
  </div></main>;
}
